/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_howell_jni_JniUtil */

#ifndef _Included_com_howell_jni_JniUtil
#define _Included_com_howell_jni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeInit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeDeinit
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeRenderY
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeRenderY
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeRenderU
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeRenderU
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeRenderV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeRenderV
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeOnSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeOnSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeAudioInit
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeAudioInit
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeAudioStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeAudioStop
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeAudioDeinit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeAudioDeinit
  (JNIEnv *, jclass);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativePlaybackPause
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativePlaybackPause
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeGetStreamCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeGetStreamCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeJoinThread
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeJoinThread
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeCreateHandle
 * Signature: (Ljava/lang/Object;Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_howell_jni_JniUtil_nativeCreateHandle
  (JNIEnv *, jclass, jobject, jstring, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativePrepareSDP
 * Signature: (JLcom/howell/entityclass/StreamReqContext;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_howell_jni_JniUtil_nativePrepareSDP
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeHandleRemoteSDP
 * Signature: (JLcom/howell/entityclass/StreamReqContext;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeHandleRemoteSDP
  (JNIEnv *, jclass, jlong, jobject, jstring, jstring);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeStart
 * Signature: (JLcom/howell/entityclass/StreamReqContext;I)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeStart
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeFreeHandle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativeFreeHandle
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativePrepareReplay
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_com_howell_jni_JniUtil_nativePrepareReplay
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeGetMethod
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeGetMethod
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeGetSdpTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeGetSdpTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeGetBegSdpTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeGetBegSdpTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeGetEndSdpTime
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeGetEndSdpTime
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeSetCatchPictureFlag
 * Signature: (JLjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeSetCatchPictureFlag
  (JNIEnv *, jclass, jlong, jstring, jint);

/*
 * Class:     com_howell_jni_JniUtil
 * Method:    nativeSetAudioData
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_com_howell_jni_JniUtil_nativeSetAudioData
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
