/* soapClient.c
   Generated by gSOAP 2.8.4 from HomeMCUService.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.4 2013-03-07 01:53:34 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__createAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__createAccountReq *ns1__createAccountReq, struct _ns1__createAccountRes *ns1__createAccountRes)
{	struct __ns1__createAccount soap_tmp___ns1__createAccount;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/createAccount";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__createAccount.ns1__createAccountReq = ns1__createAccountReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__createAccount(soap, &soap_tmp___ns1__createAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__createAccount(soap, &soap_tmp___ns1__createAccount, "-ns1:createAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__createAccount(soap, &soap_tmp___ns1__createAccount, "-ns1:createAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__createAccountRes)
		return soap_closesock(soap);
	soap_default__ns1__createAccountRes(soap, ns1__createAccountRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__createAccountRes(soap, ns1__createAccountRes, "ns1:createAccountRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateAccountReq *ns1__updateAccountReq, struct _ns1__updateAccountRes *ns1__updateAccountRes)
{	struct __ns1__updateAccount soap_tmp___ns1__updateAccount;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/updateAccount";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateAccount.ns1__updateAccountReq = ns1__updateAccountReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount, "-ns1:updateAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount, "-ns1:updateAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateAccountRes)
		return soap_closesock(soap);
	soap_default__ns1__updateAccountRes(soap, ns1__updateAccountRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updateAccountRes(soap, ns1__updateAccountRes, "ns1:updateAccountRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updatePassword(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updatePasswordReq *ns1__updatePasswordReq, struct _ns1__updatePasswordRes *ns1__updatePasswordRes)
{	struct __ns1__updatePassword soap_tmp___ns1__updatePassword;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/updatePassword";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updatePassword.ns1__updatePasswordReq = ns1__updatePasswordReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updatePassword(soap, &soap_tmp___ns1__updatePassword);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updatePassword(soap, &soap_tmp___ns1__updatePassword, "-ns1:updatePassword", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updatePassword(soap, &soap_tmp___ns1__updatePassword, "-ns1:updatePassword", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updatePasswordRes)
		return soap_closesock(soap);
	soap_default__ns1__updatePasswordRes(soap, ns1__updatePasswordRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updatePasswordRes(soap, ns1__updatePasswordRes, "ns1:updatePasswordRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryDevice(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__queryDeviceReq *ns1__queryDeviceReq, struct _ns1__queryDeviceRes *ns1__queryDeviceRes)
{	struct __ns1__queryDevice soap_tmp___ns1__queryDevice;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/queryDevice";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__queryDevice.ns1__queryDeviceReq = ns1__queryDeviceReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__queryDevice(soap, &soap_tmp___ns1__queryDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__queryDevice(soap, &soap_tmp___ns1__queryDevice, "-ns1:queryDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__queryDevice(soap, &soap_tmp___ns1__queryDevice, "-ns1:queryDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__queryDeviceRes)
		return soap_closesock(soap);
	soap_default__ns1__queryDeviceRes(soap, ns1__queryDeviceRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__queryDeviceRes(soap, ns1__queryDeviceRes, "ns1:queryDeviceRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateAppleToken(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateAppleTokenReq *ns1__updateAppleTokenReq, struct _ns1__updateAppleTokenRes *ns1__updateAppleTokenRes)
{	struct __ns1__updateAppleToken soap_tmp___ns1__updateAppleToken;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/updateAppleToken";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateAppleToken.ns1__updateAppleTokenReq = ns1__updateAppleTokenReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateAppleToken(soap, &soap_tmp___ns1__updateAppleToken);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateAppleToken(soap, &soap_tmp___ns1__updateAppleToken, "-ns1:updateAppleToken", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateAppleToken(soap, &soap_tmp___ns1__updateAppleToken, "-ns1:updateAppleToken", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateAppleTokenRes)
		return soap_closesock(soap);
	soap_default__ns1__updateAppleTokenRes(soap, ns1__updateAppleTokenRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updateAppleTokenRes(soap, ns1__updateAppleTokenRes, "ns1:updateAppleTokenRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAccount(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAccountReq *ns1__getAccountReq, struct _ns1__getAccountRes *ns1__getAccountRes)
{	struct __ns1__getAccount soap_tmp___ns1__getAccount;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getAccount";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAccount.ns1__getAccountReq = ns1__getAccountReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAccount(soap, &soap_tmp___ns1__getAccount);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAccount(soap, &soap_tmp___ns1__getAccount, "-ns1:getAccount", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAccount(soap, &soap_tmp___ns1__getAccount, "-ns1:getAccount", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAccountRes)
		return soap_closesock(soap);
	soap_default__ns1__getAccountRes(soap, ns1__getAccountRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAccountRes(soap, ns1__getAccountRes, "ns1:getAccountRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getBackPassword(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getBackPasswordReq *ns1__getBackPasswordReq, struct _ns1__getBackPasswordRes *ns1__getBackPasswordRes)
{	struct __ns1__getBackPassword soap_tmp___ns1__getBackPassword;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getBackPassword";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getBackPassword.ns1__getBackPasswordReq = ns1__getBackPasswordReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getBackPassword(soap, &soap_tmp___ns1__getBackPassword);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getBackPassword(soap, &soap_tmp___ns1__getBackPassword, "-ns1:getBackPassword", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getBackPassword(soap, &soap_tmp___ns1__getBackPassword, "-ns1:getBackPassword", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getBackPasswordRes)
		return soap_closesock(soap);
	soap_default__ns1__getBackPasswordRes(soap, ns1__getBackPasswordRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getBackPasswordRes(soap, ns1__getBackPasswordRes, "ns1:getBackPasswordRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getAuxiliary(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getAuxiliaryReq *ns1__getAuxiliaryReq, struct _ns1__getAuxiliaryRes *ns1__getAuxiliaryRes)
{	struct __ns1__getAuxiliary soap_tmp___ns1__getAuxiliary;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getAuxiliary";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getAuxiliary.ns1__getAuxiliaryReq = ns1__getAuxiliaryReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getAuxiliary(soap, &soap_tmp___ns1__getAuxiliary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getAuxiliary(soap, &soap_tmp___ns1__getAuxiliary, "-ns1:getAuxiliary", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getAuxiliary(soap, &soap_tmp___ns1__getAuxiliary, "-ns1:getAuxiliary", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getAuxiliaryRes)
		return soap_closesock(soap);
	soap_default__ns1__getAuxiliaryRes(soap, ns1__getAuxiliaryRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getAuxiliaryRes(soap, ns1__getAuxiliaryRes, "ns1:getAuxiliaryRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setAuxiliary(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setAuxiliaryReq *ns1__setAuxiliaryReq, struct _ns1__setAuxiliaryRes *ns1__setAuxiliaryRes)
{	struct __ns1__setAuxiliary soap_tmp___ns1__setAuxiliary;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/setAuxiliary";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setAuxiliary.ns1__setAuxiliaryReq = ns1__setAuxiliaryReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setAuxiliary(soap, &soap_tmp___ns1__setAuxiliary);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setAuxiliary(soap, &soap_tmp___ns1__setAuxiliary, "-ns1:setAuxiliary", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setAuxiliary(soap, &soap_tmp___ns1__setAuxiliary, "-ns1:setAuxiliary", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setAuxiliaryRes)
		return soap_closesock(soap);
	soap_default__ns1__setAuxiliaryRes(soap, ns1__setAuxiliaryRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setAuxiliaryRes(soap, ns1__setAuxiliaryRes, "ns1:setAuxiliaryRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__invite(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__inviteReq *ns1__inviteReq, struct _ns1__inviteRes *ns1__inviteRes)
{	struct __ns1__invite soap_tmp___ns1__invite;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/invite";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__invite.ns1__inviteReq = ns1__inviteReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__invite(soap, &soap_tmp___ns1__invite);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__invite(soap, &soap_tmp___ns1__invite, "-ns1:invite", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__invite(soap, &soap_tmp___ns1__invite, "-ns1:invite", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__inviteRes)
		return soap_closesock(soap);
	soap_default__ns1__inviteRes(soap, ns1__inviteRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__inviteRes(soap, ns1__inviteRes, "ns1:inviteRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__bye(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__byeReq *ns1__byeReq, struct _ns1__byeRes *ns1__byeRes)
{	struct __ns1__bye soap_tmp___ns1__bye;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/bye";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__bye.ns1__byeReq = ns1__byeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__bye(soap, &soap_tmp___ns1__bye);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__bye(soap, &soap_tmp___ns1__bye, "-ns1:bye", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__bye(soap, &soap_tmp___ns1__bye, "-ns1:bye", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__byeRes)
		return soap_closesock(soap);
	soap_default__ns1__byeRes(soap, ns1__byeRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__byeRes(soap, ns1__byeRes, "ns1:byeRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userLogin(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__userLoginReq *ns1__userLoginReq, struct _ns1__userLoginRes *ns1__userLoginRes)
{	struct __ns1__userLogin soap_tmp___ns1__userLogin;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/userLogin";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__userLogin.ns1__userLoginReq = ns1__userLoginReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__userLogin(soap, &soap_tmp___ns1__userLogin);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userLogin(soap, &soap_tmp___ns1__userLogin, "-ns1:userLogin", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userLogin(soap, &soap_tmp___ns1__userLogin, "-ns1:userLogin", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userLoginRes)
		return soap_closesock(soap);
	soap_default__ns1__userLoginRes(soap, ns1__userLoginRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__userLoginRes(soap, ns1__userLoginRes, "ns1:userLoginRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__userLogout(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__userLogoutReq *ns1__userLogoutReq, struct _ns1__userLogoutRes *ns1__userLogoutRes)
{	struct __ns1__userLogout soap_tmp___ns1__userLogout;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/userLogout";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__userLogout.ns1__userLogoutReq = ns1__userLogoutReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__userLogout(soap, &soap_tmp___ns1__userLogout);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__userLogout(soap, &soap_tmp___ns1__userLogout, "-ns1:userLogout", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__userLogout(soap, &soap_tmp___ns1__userLogout, "-ns1:userLogout", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__userLogoutRes)
		return soap_closesock(soap);
	soap_default__ns1__userLogoutRes(soap, ns1__userLogoutRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__userLogoutRes(soap, ns1__userLogoutRes, "ns1:userLogoutRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__updateChannelName(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__updateChannelNameReq *ns1__updateChannelNameReq, struct _ns1__updateChannelNameRes *ns1__updateChannelNameRes)
{	struct __ns1__updateChannelName soap_tmp___ns1__updateChannelName;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/updateChannelName";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__updateChannelName.ns1__updateChannelNameReq = ns1__updateChannelNameReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__updateChannelName(soap, &soap_tmp___ns1__updateChannelName);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__updateChannelName(soap, &soap_tmp___ns1__updateChannelName, "-ns1:updateChannelName", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__updateChannelName(soap, &soap_tmp___ns1__updateChannelName, "-ns1:updateChannelName", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__updateChannelNameRes)
		return soap_closesock(soap);
	soap_default__ns1__updateChannelNameRes(soap, ns1__updateChannelNameRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__updateChannelNameRes(soap, ns1__updateChannelNameRes, "ns1:updateChannelNameRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__addDevice(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__addDeviceReq *ns1__addDeviceReq, struct _ns1__addDeviceRes *ns1__addDeviceRes)
{	struct __ns1__addDevice soap_tmp___ns1__addDevice;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/addDevice";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__addDevice.ns1__addDeviceReq = ns1__addDeviceReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__addDevice(soap, &soap_tmp___ns1__addDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__addDevice(soap, &soap_tmp___ns1__addDevice, "-ns1:addDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__addDevice(soap, &soap_tmp___ns1__addDevice, "-ns1:addDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__addDeviceRes)
		return soap_closesock(soap);
	soap_default__ns1__addDeviceRes(soap, ns1__addDeviceRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__addDeviceRes(soap, ns1__addDeviceRes, "ns1:addDeviceRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__nullifyDevice(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__nullifyDeviceReq *ns1__nullifyDeviceReq, struct _ns1__nullifyDeviceRes *ns1__nullifyDeviceRes)
{	struct __ns1__nullifyDevice soap_tmp___ns1__nullifyDevice;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/nullifyDevice";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__nullifyDevice.ns1__nullifyDeviceReq = ns1__nullifyDeviceReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__nullifyDevice(soap, &soap_tmp___ns1__nullifyDevice);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__nullifyDevice(soap, &soap_tmp___ns1__nullifyDevice, "-ns1:nullifyDevice", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__nullifyDevice(soap, &soap_tmp___ns1__nullifyDevice, "-ns1:nullifyDevice", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__nullifyDeviceRes)
		return soap_closesock(soap);
	soap_default__ns1__nullifyDeviceRes(soap, ns1__nullifyDeviceRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__nullifyDeviceRes(soap, ns1__nullifyDeviceRes, "ns1:nullifyDeviceRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ptzControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__ptzControlReq *ns1__ptzControlReq, struct _ns1__ptzControlRes *ns1__ptzControlRes)
{	struct __ns1__ptzControl soap_tmp___ns1__ptzControl;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/ptzControl";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ptzControl.ns1__ptzControlReq = ns1__ptzControlReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__ptzControl(soap, &soap_tmp___ns1__ptzControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ptzControl(soap, &soap_tmp___ns1__ptzControl, "-ns1:ptzControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ptzControl(soap, &soap_tmp___ns1__ptzControl, "-ns1:ptzControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ptzControlRes)
		return soap_closesock(soap);
	soap_default__ns1__ptzControlRes(soap, ns1__ptzControlRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__ptzControlRes(soap, ns1__ptzControlRes, "ns1:ptzControlRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__lensControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__lensControlReq *ns1__lensControlReq, struct _ns1__lensControlRes *ns1__lensControlRes)
{	struct __ns1__lensControl soap_tmp___ns1__lensControl;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/lensControl";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__lensControl.ns1__lensControlReq = ns1__lensControlReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__lensControl(soap, &soap_tmp___ns1__lensControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__lensControl(soap, &soap_tmp___ns1__lensControl, "-ns1:lensControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__lensControl(soap, &soap_tmp___ns1__lensControl, "-ns1:lensControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__lensControlRes)
		return soap_closesock(soap);
	soap_default__ns1__lensControlRes(soap, ns1__lensControlRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__lensControlRes(soap, ns1__lensControlRes, "ns1:lensControlRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__presetControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__presetControlReq *ns1__presetControlReq, struct _ns1__presetControlRes *ns1__presetControlRes)
{	struct __ns1__presetControl soap_tmp___ns1__presetControl;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/presetControl";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__presetControl.ns1__presetControlReq = ns1__presetControlReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__presetControl(soap, &soap_tmp___ns1__presetControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__presetControl(soap, &soap_tmp___ns1__presetControl, "-ns1:presetControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__presetControl(soap, &soap_tmp___ns1__presetControl, "-ns1:presetControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__presetControlRes)
		return soap_closesock(soap);
	soap_default__ns1__presetControlRes(soap, ns1__presetControlRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__presetControlRes(soap, ns1__presetControlRes, "ns1:presetControlRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getCodingParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getCodingParamReq *ns1__getCodingParamReq, struct _ns1__getCodingParamRes *ns1__getCodingParamRes)
{	struct __ns1__getCodingParam soap_tmp___ns1__getCodingParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getCodingParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getCodingParam.ns1__getCodingParamReq = ns1__getCodingParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getCodingParam(soap, &soap_tmp___ns1__getCodingParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getCodingParam(soap, &soap_tmp___ns1__getCodingParam, "-ns1:getCodingParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getCodingParam(soap, &soap_tmp___ns1__getCodingParam, "-ns1:getCodingParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getCodingParamRes)
		return soap_closesock(soap);
	soap_default__ns1__getCodingParamRes(soap, ns1__getCodingParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getCodingParamRes(soap, ns1__getCodingParamRes, "ns1:getCodingParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setCodingParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setCodingParamReq *ns1__setCodingParamReq, struct _ns1__setCodingParamRes *ns1__setCodingParamRes)
{	struct __ns1__setCodingParam soap_tmp___ns1__setCodingParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/setCodingParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setCodingParam.ns1__setCodingParamReq = ns1__setCodingParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setCodingParam(soap, &soap_tmp___ns1__setCodingParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setCodingParam(soap, &soap_tmp___ns1__setCodingParam, "-ns1:setCodingParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setCodingParam(soap, &soap_tmp___ns1__setCodingParam, "-ns1:setCodingParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setCodingParamRes)
		return soap_closesock(soap);
	soap_default__ns1__setCodingParamRes(soap, ns1__setCodingParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setCodingParamRes(soap, ns1__setCodingParamRes, "ns1:setCodingParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__rebootReq *ns1__rebootReq, struct _ns1__rebootRes *ns1__rebootRes)
{	struct __ns1__reboot soap_tmp___ns1__reboot;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/reboot";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__reboot.ns1__rebootReq = ns1__rebootReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__reboot(soap, &soap_tmp___ns1__reboot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__reboot(soap, &soap_tmp___ns1__reboot, "-ns1:reboot", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__reboot(soap, &soap_tmp___ns1__reboot, "-ns1:reboot", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__rebootRes)
		return soap_closesock(soap);
	soap_default__ns1__rebootRes(soap, ns1__rebootRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__rebootRes(soap, ns1__rebootRes, "ns1:rebootRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getDevVer(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getDevVerReq *ns1__getDevVerReq, struct _ns1__getDevVerRes *ns1__getDevVerRes)
{	struct __ns1__getDevVer soap_tmp___ns1__getDevVer;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getDevVer";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getDevVer.ns1__getDevVerReq = ns1__getDevVerReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getDevVer(soap, &soap_tmp___ns1__getDevVer);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getDevVer(soap, &soap_tmp___ns1__getDevVer, "-ns1:getDevVer", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getDevVer(soap, &soap_tmp___ns1__getDevVer, "-ns1:getDevVer", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getDevVerRes)
		return soap_closesock(soap);
	soap_default__ns1__getDevVerRes(soap, ns1__getDevVerRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getDevVerRes(soap, ns1__getDevVerRes, "ns1:getDevVerRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__upgradeDevVer(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__upgradeDevVerReq *ns1__upgradeDevVerReq, struct _ns1__upgradeDevVerRes *ns1__upgradeDevVerRes)
{	struct __ns1__upgradeDevVer soap_tmp___ns1__upgradeDevVer;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/upgradeDevVer";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__upgradeDevVer.ns1__upgradeDevVerReq = ns1__upgradeDevVerReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__upgradeDevVer(soap, &soap_tmp___ns1__upgradeDevVer);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__upgradeDevVer(soap, &soap_tmp___ns1__upgradeDevVer, "-ns1:upgradeDevVer", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__upgradeDevVer(soap, &soap_tmp___ns1__upgradeDevVer, "-ns1:upgradeDevVer", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__upgradeDevVerRes)
		return soap_closesock(soap);
	soap_default__ns1__upgradeDevVerRes(soap, ns1__upgradeDevVerRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__upgradeDevVerRes(soap, ns1__upgradeDevVerRes, "ns1:upgradeDevVerRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__queryLogReq *ns1__queryLogReq, struct _ns1__queryLogRes *ns1__queryLogRes)
{	struct __ns1__queryLog soap_tmp___ns1__queryLog;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/queryLog";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__queryLog.ns1__queryLogReq = ns1__queryLogReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__queryLog(soap, &soap_tmp___ns1__queryLog);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__queryLog(soap, &soap_tmp___ns1__queryLog, "-ns1:queryLog", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__queryLog(soap, &soap_tmp___ns1__queryLog, "-ns1:queryLog", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__queryLogRes)
		return soap_closesock(soap);
	soap_default__ns1__queryLogRes(soap, ns1__queryLogRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__queryLogRes(soap, ns1__queryLogRes, "ns1:queryLogRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryDevLog(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__queryDevLogReq *ns1__queryDevLogReq, struct _ns1__queryDevLogRes *ns1__queryDevLogRes)
{	struct __ns1__queryDevLog soap_tmp___ns1__queryDevLog;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/queryDevLog";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__queryDevLog.ns1__queryDevLogReq = ns1__queryDevLogReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__queryDevLog(soap, &soap_tmp___ns1__queryDevLog);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__queryDevLog(soap, &soap_tmp___ns1__queryDevLog, "-ns1:queryDevLog", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__queryDevLog(soap, &soap_tmp___ns1__queryDevLog, "-ns1:queryDevLog", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__queryDevLogRes)
		return soap_closesock(soap);
	soap_default__ns1__queryDevLogRes(soap, ns1__queryDevLogRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__queryDevLogRes(soap, ns1__queryDevLogRes, "ns1:queryDevLogRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getVideoParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getVideoParamReq *ns1__getVideoParamReq, struct _ns1__getVideoParamRes *ns1__getVideoParamRes)
{	struct __ns1__getVideoParam soap_tmp___ns1__getVideoParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getVideoParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getVideoParam.ns1__getVideoParamReq = ns1__getVideoParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getVideoParam(soap, &soap_tmp___ns1__getVideoParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getVideoParam(soap, &soap_tmp___ns1__getVideoParam, "-ns1:getVideoParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getVideoParam(soap, &soap_tmp___ns1__getVideoParam, "-ns1:getVideoParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getVideoParamRes)
		return soap_closesock(soap);
	soap_default__ns1__getVideoParamRes(soap, ns1__getVideoParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getVideoParamRes(soap, ns1__getVideoParamRes, "ns1:getVideoParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setVideoParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setVideoParamReq *ns1__setVideoParamReq, struct _ns1__setVideoParamRes *ns1__setVideoParamRes)
{	struct __ns1__setVideoParam soap_tmp___ns1__setVideoParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/setVideoParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setVideoParam.ns1__setVideoParamReq = ns1__setVideoParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setVideoParam(soap, &soap_tmp___ns1__setVideoParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setVideoParam(soap, &soap_tmp___ns1__setVideoParam, "-ns1:setVideoParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setVideoParam(soap, &soap_tmp___ns1__setVideoParam, "-ns1:setVideoParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setVideoParamRes)
		return soap_closesock(soap);
	soap_default__ns1__setVideoParamRes(soap, ns1__setVideoParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setVideoParamRes(soap, ns1__setVideoParamRes, "ns1:setVideoParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getOSDParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getOSDParamReq *ns1__getOSDParamReq, struct _ns1__getOSDParamRes *ns1__getOSDParamRes)
{	struct __ns1__getOSDParam soap_tmp___ns1__getOSDParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getOSDParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getOSDParam.ns1__getOSDParamReq = ns1__getOSDParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getOSDParam(soap, &soap_tmp___ns1__getOSDParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getOSDParam(soap, &soap_tmp___ns1__getOSDParam, "-ns1:getOSDParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getOSDParam(soap, &soap_tmp___ns1__getOSDParam, "-ns1:getOSDParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getOSDParamRes)
		return soap_closesock(soap);
	soap_default__ns1__getOSDParamRes(soap, ns1__getOSDParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getOSDParamRes(soap, ns1__getOSDParamRes, "ns1:getOSDParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setOSDParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setOSDParamReq *ns1__setOSDParamReq, struct _ns1__setOSDParamRes *ns1__setOSDParamRes)
{	struct __ns1__setOSDParam soap_tmp___ns1__setOSDParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/setOSDParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setOSDParam.ns1__setOSDParamReq = ns1__setOSDParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setOSDParam(soap, &soap_tmp___ns1__setOSDParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setOSDParam(soap, &soap_tmp___ns1__setOSDParam, "-ns1:setOSDParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setOSDParam(soap, &soap_tmp___ns1__setOSDParam, "-ns1:setOSDParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setOSDParamRes)
		return soap_closesock(soap);
	soap_default__ns1__setOSDParamRes(soap, ns1__setOSDParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setOSDParamRes(soap, ns1__setOSDParamRes, "ns1:setOSDParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getTimeReq *ns1__getTimeReq, struct _ns1__getTimeRes *ns1__getTimeRes)
{	struct __ns1__getTime soap_tmp___ns1__getTime;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getTime";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getTime.ns1__getTimeReq = ns1__getTimeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getTime(soap, &soap_tmp___ns1__getTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getTime(soap, &soap_tmp___ns1__getTime, "-ns1:getTime", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getTime(soap, &soap_tmp___ns1__getTime, "-ns1:getTime", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getTimeRes)
		return soap_closesock(soap);
	soap_default__ns1__getTimeRes(soap, ns1__getTimeRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getTimeRes(soap, ns1__getTimeRes, "ns1:getTimeRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setTimeReq *ns1__setTimeReq, struct _ns1__setTimeRes *ns1__setTimeRes)
{	struct __ns1__setTime soap_tmp___ns1__setTime;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/setTime";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setTime.ns1__setTimeReq = ns1__setTimeReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setTime(soap, &soap_tmp___ns1__setTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setTime(soap, &soap_tmp___ns1__setTime, "-ns1:setTime", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setTime(soap, &soap_tmp___ns1__setTime, "-ns1:setTime", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setTimeRes)
		return soap_closesock(soap);
	soap_default__ns1__setTimeRes(soap, ns1__setTimeRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setTimeRes(soap, ns1__setTimeRes, "ns1:setTimeRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getVMDParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getVMDParamReq *ns1__getVMDParamReq, struct _ns1__getVMDParamRes *ns1__getVMDParamRes)
{	struct __ns1__getVMDParam soap_tmp___ns1__getVMDParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getVMDParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getVMDParam.ns1__getVMDParamReq = ns1__getVMDParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getVMDParam(soap, &soap_tmp___ns1__getVMDParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getVMDParam(soap, &soap_tmp___ns1__getVMDParam, "-ns1:getVMDParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getVMDParam(soap, &soap_tmp___ns1__getVMDParam, "-ns1:getVMDParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getVMDParamRes)
		return soap_closesock(soap);
	soap_default__ns1__getVMDParamRes(soap, ns1__getVMDParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getVMDParamRes(soap, ns1__getVMDParamRes, "ns1:getVMDParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setVMDParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setVMDParamReq *ns1__setVMDParamReq, struct _ns1__setVMDParamRes *ns1__setVMDParamRes)
{	struct __ns1__setVMDParam soap_tmp___ns1__setVMDParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/setVMDParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setVMDParam.ns1__setVMDParamReq = ns1__setVMDParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setVMDParam(soap, &soap_tmp___ns1__setVMDParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setVMDParam(soap, &soap_tmp___ns1__setVMDParam, "-ns1:setVMDParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setVMDParam(soap, &soap_tmp___ns1__setVMDParam, "-ns1:setVMDParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setVMDParamRes)
		return soap_closesock(soap);
	soap_default__ns1__setVMDParamRes(soap, ns1__setVMDParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setVMDParamRes(soap, ns1__setVMDParamRes, "ns1:setVMDParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getPrivacyMaskParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getPrivacyMaskParamReq *ns1__getPrivacyMaskParamReq, struct _ns1__getPrivacyMaskParamRes *ns1__getPrivacyMaskParamRes)
{	struct __ns1__getPrivacyMaskParam soap_tmp___ns1__getPrivacyMaskParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getPrivacyMaskParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getPrivacyMaskParam.ns1__getPrivacyMaskParamReq = ns1__getPrivacyMaskParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getPrivacyMaskParam(soap, &soap_tmp___ns1__getPrivacyMaskParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getPrivacyMaskParam(soap, &soap_tmp___ns1__getPrivacyMaskParam, "-ns1:getPrivacyMaskParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getPrivacyMaskParam(soap, &soap_tmp___ns1__getPrivacyMaskParam, "-ns1:getPrivacyMaskParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getPrivacyMaskParamRes)
		return soap_closesock(soap);
	soap_default__ns1__getPrivacyMaskParamRes(soap, ns1__getPrivacyMaskParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getPrivacyMaskParamRes(soap, ns1__getPrivacyMaskParamRes, "ns1:getPrivacyMaskParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__setPrivacyMaskParam(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__setPrivacyMaskParamReq *ns1__setPrivacyMaskParamReq, struct _ns1__setPrivacyMaskParamRes *ns1__setPrivacyMaskParamRes)
{	struct __ns1__setPrivacyMaskParam soap_tmp___ns1__setPrivacyMaskParam;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/setPrivacyMaskParam";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__setPrivacyMaskParam.ns1__setPrivacyMaskParamReq = ns1__setPrivacyMaskParamReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__setPrivacyMaskParam(soap, &soap_tmp___ns1__setPrivacyMaskParam);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__setPrivacyMaskParam(soap, &soap_tmp___ns1__setPrivacyMaskParam, "-ns1:setPrivacyMaskParam", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__setPrivacyMaskParam(soap, &soap_tmp___ns1__setPrivacyMaskParam, "-ns1:setPrivacyMaskParam", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__setPrivacyMaskParamRes)
		return soap_closesock(soap);
	soap_default__ns1__setPrivacyMaskParamRes(soap, ns1__setPrivacyMaskParamRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__setPrivacyMaskParamRes(soap, ns1__setPrivacyMaskParamRes, "ns1:setPrivacyMaskParamRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getPlayUrl(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getPlayUrlReq *ns1__getPlayUrlReq, struct _ns1__getPlayUrlRes *ns1__getPlayUrlRes)
{	struct __ns1__getPlayUrl soap_tmp___ns1__getPlayUrl;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getPlayUrl";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getPlayUrl.ns1__getPlayUrlReq = ns1__getPlayUrlReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getPlayUrl(soap, &soap_tmp___ns1__getPlayUrl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getPlayUrl(soap, &soap_tmp___ns1__getPlayUrl, "-ns1:getPlayUrl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getPlayUrl(soap, &soap_tmp___ns1__getPlayUrl, "-ns1:getPlayUrl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getPlayUrlRes)
		return soap_closesock(soap);
	soap_default__ns1__getPlayUrlRes(soap, ns1__getPlayUrlRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getPlayUrlRes(soap, ns1__getPlayUrlRes, "ns1:getPlayUrlRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__getVODUrl(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__getVODUrlReq *ns1__getVODUrlReq, struct _ns1__getVODUrlRes *ns1__getVODUrlRes)
{	struct __ns1__getVODUrl soap_tmp___ns1__getVODUrl;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/getVODUrl";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__getVODUrl.ns1__getVODUrlReq = ns1__getVODUrlReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__getVODUrl(soap, &soap_tmp___ns1__getVODUrl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__getVODUrl(soap, &soap_tmp___ns1__getVODUrl, "-ns1:getVODUrl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__getVODUrl(soap, &soap_tmp___ns1__getVODUrl, "-ns1:getVODUrl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__getVODUrlRes)
		return soap_closesock(soap);
	soap_default__ns1__getVODUrlRes(soap, ns1__getVODUrlRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__getVODUrlRes(soap, ns1__getVODUrlRes, "ns1:getVODUrlRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__vodSearch(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _ns1__vodSearchReq *ns1__vodSearchReq, struct _ns1__vodSearchRes *ns1__vodSearchRes)
{	struct __ns1__vodSearch soap_tmp___ns1__vodSearch;
	if (!soap_endpoint)
		soap_endpoint = "http://www.haoweis.com:8800/HomeService/HomeMCUService.svc";
	if (!soap_action)
		soap_action = "http://www.haoweis.com/HomeServices/MCU/vodSearch";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__vodSearch.ns1__vodSearchReq = ns1__vodSearchReq;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__vodSearch(soap, &soap_tmp___ns1__vodSearch);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__vodSearch(soap, &soap_tmp___ns1__vodSearch, "-ns1:vodSearch", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__vodSearch(soap, &soap_tmp___ns1__vodSearch, "-ns1:vodSearch", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__vodSearchRes)
		return soap_closesock(soap);
	soap_default__ns1__vodSearchRes(soap, ns1__vodSearchRes);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__ns1__vodSearchRes(soap, ns1__vodSearchRes, "ns1:vodSearchRes", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
