/* soapServer.c
   Generated by gSOAP 2.8.4 from HomeMCUService.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.4 2013-03-07 01:53:34 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:createAccountReq"))
		return soap_serve___ns1__createAccount(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:updateAccountReq"))
		return soap_serve___ns1__updateAccount(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:updatePasswordReq"))
		return soap_serve___ns1__updatePassword(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:queryDeviceReq"))
		return soap_serve___ns1__queryDevice(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:updateAppleTokenReq"))
		return soap_serve___ns1__updateAppleToken(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getAccountReq"))
		return soap_serve___ns1__getAccount(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getBackPasswordReq"))
		return soap_serve___ns1__getBackPassword(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getAuxiliaryReq"))
		return soap_serve___ns1__getAuxiliary(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setAuxiliaryReq"))
		return soap_serve___ns1__setAuxiliary(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:inviteReq"))
		return soap_serve___ns1__invite(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:byeReq"))
		return soap_serve___ns1__bye(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:userLoginReq"))
		return soap_serve___ns1__userLogin(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:userLogoutReq"))
		return soap_serve___ns1__userLogout(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:updateChannelNameReq"))
		return soap_serve___ns1__updateChannelName(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:addDeviceReq"))
		return soap_serve___ns1__addDevice(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:nullifyDeviceReq"))
		return soap_serve___ns1__nullifyDevice(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ptzControlReq"))
		return soap_serve___ns1__ptzControl(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:lensControlReq"))
		return soap_serve___ns1__lensControl(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:presetControlReq"))
		return soap_serve___ns1__presetControl(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getCodingParamReq"))
		return soap_serve___ns1__getCodingParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setCodingParamReq"))
		return soap_serve___ns1__setCodingParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:rebootReq"))
		return soap_serve___ns1__reboot(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getDevVerReq"))
		return soap_serve___ns1__getDevVer(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:upgradeDevVerReq"))
		return soap_serve___ns1__upgradeDevVer(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:queryLogReq"))
		return soap_serve___ns1__queryLog(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:queryDevLogReq"))
		return soap_serve___ns1__queryDevLog(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getVideoParamReq"))
		return soap_serve___ns1__getVideoParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setVideoParamReq"))
		return soap_serve___ns1__setVideoParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getOSDParamReq"))
		return soap_serve___ns1__getOSDParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setOSDParamReq"))
		return soap_serve___ns1__setOSDParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getTimeReq"))
		return soap_serve___ns1__getTime(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setTimeReq"))
		return soap_serve___ns1__setTime(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getVMDParamReq"))
		return soap_serve___ns1__getVMDParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setVMDParamReq"))
		return soap_serve___ns1__setVMDParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getPrivacyMaskParamReq"))
		return soap_serve___ns1__getPrivacyMaskParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:setPrivacyMaskParamReq"))
		return soap_serve___ns1__setPrivacyMaskParam(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getPlayUrlReq"))
		return soap_serve___ns1__getPlayUrl(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:getVODUrlReq"))
		return soap_serve___ns1__getVODUrl(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:vodSearchReq"))
		return soap_serve___ns1__vodSearch(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__createAccount(struct soap *soap)
{	struct __ns1__createAccount soap_tmp___ns1__createAccount;
	struct _ns1__createAccountRes ns1__createAccountRes;
	soap_default__ns1__createAccountRes(soap, &ns1__createAccountRes);
	soap_default___ns1__createAccount(soap, &soap_tmp___ns1__createAccount);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__createAccount(soap, &soap_tmp___ns1__createAccount, "-ns1:createAccount", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__createAccount(soap, soap_tmp___ns1__createAccount.ns1__createAccountReq, &ns1__createAccountRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__createAccountRes(soap, &ns1__createAccountRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__createAccountRes(soap, &ns1__createAccountRes, "ns1:createAccountRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__createAccountRes(soap, &ns1__createAccountRes, "ns1:createAccountRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__updateAccount(struct soap *soap)
{	struct __ns1__updateAccount soap_tmp___ns1__updateAccount;
	struct _ns1__updateAccountRes ns1__updateAccountRes;
	soap_default__ns1__updateAccountRes(soap, &ns1__updateAccountRes);
	soap_default___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__updateAccount(soap, &soap_tmp___ns1__updateAccount, "-ns1:updateAccount", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__updateAccount(soap, soap_tmp___ns1__updateAccount.ns1__updateAccountReq, &ns1__updateAccountRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__updateAccountRes(soap, &ns1__updateAccountRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__updateAccountRes(soap, &ns1__updateAccountRes, "ns1:updateAccountRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__updateAccountRes(soap, &ns1__updateAccountRes, "ns1:updateAccountRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__updatePassword(struct soap *soap)
{	struct __ns1__updatePassword soap_tmp___ns1__updatePassword;
	struct _ns1__updatePasswordRes ns1__updatePasswordRes;
	soap_default__ns1__updatePasswordRes(soap, &ns1__updatePasswordRes);
	soap_default___ns1__updatePassword(soap, &soap_tmp___ns1__updatePassword);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__updatePassword(soap, &soap_tmp___ns1__updatePassword, "-ns1:updatePassword", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__updatePassword(soap, soap_tmp___ns1__updatePassword.ns1__updatePasswordReq, &ns1__updatePasswordRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__updatePasswordRes(soap, &ns1__updatePasswordRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__updatePasswordRes(soap, &ns1__updatePasswordRes, "ns1:updatePasswordRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__updatePasswordRes(soap, &ns1__updatePasswordRes, "ns1:updatePasswordRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__queryDevice(struct soap *soap)
{	struct __ns1__queryDevice soap_tmp___ns1__queryDevice;
	struct _ns1__queryDeviceRes ns1__queryDeviceRes;
	soap_default__ns1__queryDeviceRes(soap, &ns1__queryDeviceRes);
	soap_default___ns1__queryDevice(soap, &soap_tmp___ns1__queryDevice);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__queryDevice(soap, &soap_tmp___ns1__queryDevice, "-ns1:queryDevice", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__queryDevice(soap, soap_tmp___ns1__queryDevice.ns1__queryDeviceReq, &ns1__queryDeviceRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__queryDeviceRes(soap, &ns1__queryDeviceRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__queryDeviceRes(soap, &ns1__queryDeviceRes, "ns1:queryDeviceRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__queryDeviceRes(soap, &ns1__queryDeviceRes, "ns1:queryDeviceRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__updateAppleToken(struct soap *soap)
{	struct __ns1__updateAppleToken soap_tmp___ns1__updateAppleToken;
	struct _ns1__updateAppleTokenRes ns1__updateAppleTokenRes;
	soap_default__ns1__updateAppleTokenRes(soap, &ns1__updateAppleTokenRes);
	soap_default___ns1__updateAppleToken(soap, &soap_tmp___ns1__updateAppleToken);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__updateAppleToken(soap, &soap_tmp___ns1__updateAppleToken, "-ns1:updateAppleToken", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__updateAppleToken(soap, soap_tmp___ns1__updateAppleToken.ns1__updateAppleTokenReq, &ns1__updateAppleTokenRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__updateAppleTokenRes(soap, &ns1__updateAppleTokenRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__updateAppleTokenRes(soap, &ns1__updateAppleTokenRes, "ns1:updateAppleTokenRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__updateAppleTokenRes(soap, &ns1__updateAppleTokenRes, "ns1:updateAppleTokenRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getAccount(struct soap *soap)
{	struct __ns1__getAccount soap_tmp___ns1__getAccount;
	struct _ns1__getAccountRes ns1__getAccountRes;
	soap_default__ns1__getAccountRes(soap, &ns1__getAccountRes);
	soap_default___ns1__getAccount(soap, &soap_tmp___ns1__getAccount);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getAccount(soap, &soap_tmp___ns1__getAccount, "-ns1:getAccount", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getAccount(soap, soap_tmp___ns1__getAccount.ns1__getAccountReq, &ns1__getAccountRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getAccountRes(soap, &ns1__getAccountRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getAccountRes(soap, &ns1__getAccountRes, "ns1:getAccountRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getAccountRes(soap, &ns1__getAccountRes, "ns1:getAccountRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getBackPassword(struct soap *soap)
{	struct __ns1__getBackPassword soap_tmp___ns1__getBackPassword;
	struct _ns1__getBackPasswordRes ns1__getBackPasswordRes;
	soap_default__ns1__getBackPasswordRes(soap, &ns1__getBackPasswordRes);
	soap_default___ns1__getBackPassword(soap, &soap_tmp___ns1__getBackPassword);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getBackPassword(soap, &soap_tmp___ns1__getBackPassword, "-ns1:getBackPassword", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getBackPassword(soap, soap_tmp___ns1__getBackPassword.ns1__getBackPasswordReq, &ns1__getBackPasswordRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getBackPasswordRes(soap, &ns1__getBackPasswordRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getBackPasswordRes(soap, &ns1__getBackPasswordRes, "ns1:getBackPasswordRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getBackPasswordRes(soap, &ns1__getBackPasswordRes, "ns1:getBackPasswordRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getAuxiliary(struct soap *soap)
{	struct __ns1__getAuxiliary soap_tmp___ns1__getAuxiliary;
	struct _ns1__getAuxiliaryRes ns1__getAuxiliaryRes;
	soap_default__ns1__getAuxiliaryRes(soap, &ns1__getAuxiliaryRes);
	soap_default___ns1__getAuxiliary(soap, &soap_tmp___ns1__getAuxiliary);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getAuxiliary(soap, &soap_tmp___ns1__getAuxiliary, "-ns1:getAuxiliary", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getAuxiliary(soap, soap_tmp___ns1__getAuxiliary.ns1__getAuxiliaryReq, &ns1__getAuxiliaryRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getAuxiliaryRes(soap, &ns1__getAuxiliaryRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getAuxiliaryRes(soap, &ns1__getAuxiliaryRes, "ns1:getAuxiliaryRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getAuxiliaryRes(soap, &ns1__getAuxiliaryRes, "ns1:getAuxiliaryRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__setAuxiliary(struct soap *soap)
{	struct __ns1__setAuxiliary soap_tmp___ns1__setAuxiliary;
	struct _ns1__setAuxiliaryRes ns1__setAuxiliaryRes;
	soap_default__ns1__setAuxiliaryRes(soap, &ns1__setAuxiliaryRes);
	soap_default___ns1__setAuxiliary(soap, &soap_tmp___ns1__setAuxiliary);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__setAuxiliary(soap, &soap_tmp___ns1__setAuxiliary, "-ns1:setAuxiliary", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__setAuxiliary(soap, soap_tmp___ns1__setAuxiliary.ns1__setAuxiliaryReq, &ns1__setAuxiliaryRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__setAuxiliaryRes(soap, &ns1__setAuxiliaryRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__setAuxiliaryRes(soap, &ns1__setAuxiliaryRes, "ns1:setAuxiliaryRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__setAuxiliaryRes(soap, &ns1__setAuxiliaryRes, "ns1:setAuxiliaryRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__invite(struct soap *soap)
{	struct __ns1__invite soap_tmp___ns1__invite;
	struct _ns1__inviteRes ns1__inviteRes;
	soap_default__ns1__inviteRes(soap, &ns1__inviteRes);
	soap_default___ns1__invite(soap, &soap_tmp___ns1__invite);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__invite(soap, &soap_tmp___ns1__invite, "-ns1:invite", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__invite(soap, soap_tmp___ns1__invite.ns1__inviteReq, &ns1__inviteRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__inviteRes(soap, &ns1__inviteRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__inviteRes(soap, &ns1__inviteRes, "ns1:inviteRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__inviteRes(soap, &ns1__inviteRes, "ns1:inviteRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__bye(struct soap *soap)
{	struct __ns1__bye soap_tmp___ns1__bye;
	struct _ns1__byeRes ns1__byeRes;
	soap_default__ns1__byeRes(soap, &ns1__byeRes);
	soap_default___ns1__bye(soap, &soap_tmp___ns1__bye);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__bye(soap, &soap_tmp___ns1__bye, "-ns1:bye", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__bye(soap, soap_tmp___ns1__bye.ns1__byeReq, &ns1__byeRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__byeRes(soap, &ns1__byeRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__byeRes(soap, &ns1__byeRes, "ns1:byeRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__byeRes(soap, &ns1__byeRes, "ns1:byeRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userLogin(struct soap *soap)
{	struct __ns1__userLogin soap_tmp___ns1__userLogin;
	struct _ns1__userLoginRes ns1__userLoginRes;
	soap_default__ns1__userLoginRes(soap, &ns1__userLoginRes);
	soap_default___ns1__userLogin(soap, &soap_tmp___ns1__userLogin);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__userLogin(soap, &soap_tmp___ns1__userLogin, "-ns1:userLogin", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__userLogin(soap, soap_tmp___ns1__userLogin.ns1__userLoginReq, &ns1__userLoginRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__userLoginRes(soap, &ns1__userLoginRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__userLoginRes(soap, &ns1__userLoginRes, "ns1:userLoginRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__userLoginRes(soap, &ns1__userLoginRes, "ns1:userLoginRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__userLogout(struct soap *soap)
{	struct __ns1__userLogout soap_tmp___ns1__userLogout;
	struct _ns1__userLogoutRes ns1__userLogoutRes;
	soap_default__ns1__userLogoutRes(soap, &ns1__userLogoutRes);
	soap_default___ns1__userLogout(soap, &soap_tmp___ns1__userLogout);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__userLogout(soap, &soap_tmp___ns1__userLogout, "-ns1:userLogout", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__userLogout(soap, soap_tmp___ns1__userLogout.ns1__userLogoutReq, &ns1__userLogoutRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__userLogoutRes(soap, &ns1__userLogoutRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__userLogoutRes(soap, &ns1__userLogoutRes, "ns1:userLogoutRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__userLogoutRes(soap, &ns1__userLogoutRes, "ns1:userLogoutRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__updateChannelName(struct soap *soap)
{	struct __ns1__updateChannelName soap_tmp___ns1__updateChannelName;
	struct _ns1__updateChannelNameRes ns1__updateChannelNameRes;
	soap_default__ns1__updateChannelNameRes(soap, &ns1__updateChannelNameRes);
	soap_default___ns1__updateChannelName(soap, &soap_tmp___ns1__updateChannelName);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__updateChannelName(soap, &soap_tmp___ns1__updateChannelName, "-ns1:updateChannelName", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__updateChannelName(soap, soap_tmp___ns1__updateChannelName.ns1__updateChannelNameReq, &ns1__updateChannelNameRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__updateChannelNameRes(soap, &ns1__updateChannelNameRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__updateChannelNameRes(soap, &ns1__updateChannelNameRes, "ns1:updateChannelNameRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__updateChannelNameRes(soap, &ns1__updateChannelNameRes, "ns1:updateChannelNameRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__addDevice(struct soap *soap)
{	struct __ns1__addDevice soap_tmp___ns1__addDevice;
	struct _ns1__addDeviceRes ns1__addDeviceRes;
	soap_default__ns1__addDeviceRes(soap, &ns1__addDeviceRes);
	soap_default___ns1__addDevice(soap, &soap_tmp___ns1__addDevice);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__addDevice(soap, &soap_tmp___ns1__addDevice, "-ns1:addDevice", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__addDevice(soap, soap_tmp___ns1__addDevice.ns1__addDeviceReq, &ns1__addDeviceRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__addDeviceRes(soap, &ns1__addDeviceRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__addDeviceRes(soap, &ns1__addDeviceRes, "ns1:addDeviceRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__addDeviceRes(soap, &ns1__addDeviceRes, "ns1:addDeviceRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__nullifyDevice(struct soap *soap)
{	struct __ns1__nullifyDevice soap_tmp___ns1__nullifyDevice;
	struct _ns1__nullifyDeviceRes ns1__nullifyDeviceRes;
	soap_default__ns1__nullifyDeviceRes(soap, &ns1__nullifyDeviceRes);
	soap_default___ns1__nullifyDevice(soap, &soap_tmp___ns1__nullifyDevice);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__nullifyDevice(soap, &soap_tmp___ns1__nullifyDevice, "-ns1:nullifyDevice", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__nullifyDevice(soap, soap_tmp___ns1__nullifyDevice.ns1__nullifyDeviceReq, &ns1__nullifyDeviceRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__nullifyDeviceRes(soap, &ns1__nullifyDeviceRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__nullifyDeviceRes(soap, &ns1__nullifyDeviceRes, "ns1:nullifyDeviceRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__nullifyDeviceRes(soap, &ns1__nullifyDeviceRes, "ns1:nullifyDeviceRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ptzControl(struct soap *soap)
{	struct __ns1__ptzControl soap_tmp___ns1__ptzControl;
	struct _ns1__ptzControlRes ns1__ptzControlRes;
	soap_default__ns1__ptzControlRes(soap, &ns1__ptzControlRes);
	soap_default___ns1__ptzControl(soap, &soap_tmp___ns1__ptzControl);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__ptzControl(soap, &soap_tmp___ns1__ptzControl, "-ns1:ptzControl", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__ptzControl(soap, soap_tmp___ns1__ptzControl.ns1__ptzControlReq, &ns1__ptzControlRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__ptzControlRes(soap, &ns1__ptzControlRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__ptzControlRes(soap, &ns1__ptzControlRes, "ns1:ptzControlRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__ptzControlRes(soap, &ns1__ptzControlRes, "ns1:ptzControlRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__lensControl(struct soap *soap)
{	struct __ns1__lensControl soap_tmp___ns1__lensControl;
	struct _ns1__lensControlRes ns1__lensControlRes;
	soap_default__ns1__lensControlRes(soap, &ns1__lensControlRes);
	soap_default___ns1__lensControl(soap, &soap_tmp___ns1__lensControl);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__lensControl(soap, &soap_tmp___ns1__lensControl, "-ns1:lensControl", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__lensControl(soap, soap_tmp___ns1__lensControl.ns1__lensControlReq, &ns1__lensControlRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__lensControlRes(soap, &ns1__lensControlRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__lensControlRes(soap, &ns1__lensControlRes, "ns1:lensControlRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__lensControlRes(soap, &ns1__lensControlRes, "ns1:lensControlRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__presetControl(struct soap *soap)
{	struct __ns1__presetControl soap_tmp___ns1__presetControl;
	struct _ns1__presetControlRes ns1__presetControlRes;
	soap_default__ns1__presetControlRes(soap, &ns1__presetControlRes);
	soap_default___ns1__presetControl(soap, &soap_tmp___ns1__presetControl);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__presetControl(soap, &soap_tmp___ns1__presetControl, "-ns1:presetControl", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__presetControl(soap, soap_tmp___ns1__presetControl.ns1__presetControlReq, &ns1__presetControlRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__presetControlRes(soap, &ns1__presetControlRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__presetControlRes(soap, &ns1__presetControlRes, "ns1:presetControlRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__presetControlRes(soap, &ns1__presetControlRes, "ns1:presetControlRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getCodingParam(struct soap *soap)
{	struct __ns1__getCodingParam soap_tmp___ns1__getCodingParam;
	struct _ns1__getCodingParamRes ns1__getCodingParamRes;
	soap_default__ns1__getCodingParamRes(soap, &ns1__getCodingParamRes);
	soap_default___ns1__getCodingParam(soap, &soap_tmp___ns1__getCodingParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getCodingParam(soap, &soap_tmp___ns1__getCodingParam, "-ns1:getCodingParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getCodingParam(soap, soap_tmp___ns1__getCodingParam.ns1__getCodingParamReq, &ns1__getCodingParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getCodingParamRes(soap, &ns1__getCodingParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getCodingParamRes(soap, &ns1__getCodingParamRes, "ns1:getCodingParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getCodingParamRes(soap, &ns1__getCodingParamRes, "ns1:getCodingParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__setCodingParam(struct soap *soap)
{	struct __ns1__setCodingParam soap_tmp___ns1__setCodingParam;
	struct _ns1__setCodingParamRes ns1__setCodingParamRes;
	soap_default__ns1__setCodingParamRes(soap, &ns1__setCodingParamRes);
	soap_default___ns1__setCodingParam(soap, &soap_tmp___ns1__setCodingParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__setCodingParam(soap, &soap_tmp___ns1__setCodingParam, "-ns1:setCodingParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__setCodingParam(soap, soap_tmp___ns1__setCodingParam.ns1__setCodingParamReq, &ns1__setCodingParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__setCodingParamRes(soap, &ns1__setCodingParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__setCodingParamRes(soap, &ns1__setCodingParamRes, "ns1:setCodingParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__setCodingParamRes(soap, &ns1__setCodingParamRes, "ns1:setCodingParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__reboot(struct soap *soap)
{	struct __ns1__reboot soap_tmp___ns1__reboot;
	struct _ns1__rebootRes ns1__rebootRes;
	soap_default__ns1__rebootRes(soap, &ns1__rebootRes);
	soap_default___ns1__reboot(soap, &soap_tmp___ns1__reboot);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__reboot(soap, &soap_tmp___ns1__reboot, "-ns1:reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__reboot(soap, soap_tmp___ns1__reboot.ns1__rebootReq, &ns1__rebootRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__rebootRes(soap, &ns1__rebootRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__rebootRes(soap, &ns1__rebootRes, "ns1:rebootRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__rebootRes(soap, &ns1__rebootRes, "ns1:rebootRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getDevVer(struct soap *soap)
{	struct __ns1__getDevVer soap_tmp___ns1__getDevVer;
	struct _ns1__getDevVerRes ns1__getDevVerRes;
	soap_default__ns1__getDevVerRes(soap, &ns1__getDevVerRes);
	soap_default___ns1__getDevVer(soap, &soap_tmp___ns1__getDevVer);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getDevVer(soap, &soap_tmp___ns1__getDevVer, "-ns1:getDevVer", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getDevVer(soap, soap_tmp___ns1__getDevVer.ns1__getDevVerReq, &ns1__getDevVerRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getDevVerRes(soap, &ns1__getDevVerRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getDevVerRes(soap, &ns1__getDevVerRes, "ns1:getDevVerRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getDevVerRes(soap, &ns1__getDevVerRes, "ns1:getDevVerRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__upgradeDevVer(struct soap *soap)
{	struct __ns1__upgradeDevVer soap_tmp___ns1__upgradeDevVer;
	struct _ns1__upgradeDevVerRes ns1__upgradeDevVerRes;
	soap_default__ns1__upgradeDevVerRes(soap, &ns1__upgradeDevVerRes);
	soap_default___ns1__upgradeDevVer(soap, &soap_tmp___ns1__upgradeDevVer);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__upgradeDevVer(soap, &soap_tmp___ns1__upgradeDevVer, "-ns1:upgradeDevVer", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__upgradeDevVer(soap, soap_tmp___ns1__upgradeDevVer.ns1__upgradeDevVerReq, &ns1__upgradeDevVerRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__upgradeDevVerRes(soap, &ns1__upgradeDevVerRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__upgradeDevVerRes(soap, &ns1__upgradeDevVerRes, "ns1:upgradeDevVerRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__upgradeDevVerRes(soap, &ns1__upgradeDevVerRes, "ns1:upgradeDevVerRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__queryLog(struct soap *soap)
{	struct __ns1__queryLog soap_tmp___ns1__queryLog;
	struct _ns1__queryLogRes ns1__queryLogRes;
	soap_default__ns1__queryLogRes(soap, &ns1__queryLogRes);
	soap_default___ns1__queryLog(soap, &soap_tmp___ns1__queryLog);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__queryLog(soap, &soap_tmp___ns1__queryLog, "-ns1:queryLog", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__queryLog(soap, soap_tmp___ns1__queryLog.ns1__queryLogReq, &ns1__queryLogRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__queryLogRes(soap, &ns1__queryLogRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__queryLogRes(soap, &ns1__queryLogRes, "ns1:queryLogRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__queryLogRes(soap, &ns1__queryLogRes, "ns1:queryLogRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__queryDevLog(struct soap *soap)
{	struct __ns1__queryDevLog soap_tmp___ns1__queryDevLog;
	struct _ns1__queryDevLogRes ns1__queryDevLogRes;
	soap_default__ns1__queryDevLogRes(soap, &ns1__queryDevLogRes);
	soap_default___ns1__queryDevLog(soap, &soap_tmp___ns1__queryDevLog);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__queryDevLog(soap, &soap_tmp___ns1__queryDevLog, "-ns1:queryDevLog", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__queryDevLog(soap, soap_tmp___ns1__queryDevLog.ns1__queryDevLogReq, &ns1__queryDevLogRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__queryDevLogRes(soap, &ns1__queryDevLogRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__queryDevLogRes(soap, &ns1__queryDevLogRes, "ns1:queryDevLogRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__queryDevLogRes(soap, &ns1__queryDevLogRes, "ns1:queryDevLogRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getVideoParam(struct soap *soap)
{	struct __ns1__getVideoParam soap_tmp___ns1__getVideoParam;
	struct _ns1__getVideoParamRes ns1__getVideoParamRes;
	soap_default__ns1__getVideoParamRes(soap, &ns1__getVideoParamRes);
	soap_default___ns1__getVideoParam(soap, &soap_tmp___ns1__getVideoParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getVideoParam(soap, &soap_tmp___ns1__getVideoParam, "-ns1:getVideoParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getVideoParam(soap, soap_tmp___ns1__getVideoParam.ns1__getVideoParamReq, &ns1__getVideoParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getVideoParamRes(soap, &ns1__getVideoParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getVideoParamRes(soap, &ns1__getVideoParamRes, "ns1:getVideoParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getVideoParamRes(soap, &ns1__getVideoParamRes, "ns1:getVideoParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__setVideoParam(struct soap *soap)
{	struct __ns1__setVideoParam soap_tmp___ns1__setVideoParam;
	struct _ns1__setVideoParamRes ns1__setVideoParamRes;
	soap_default__ns1__setVideoParamRes(soap, &ns1__setVideoParamRes);
	soap_default___ns1__setVideoParam(soap, &soap_tmp___ns1__setVideoParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__setVideoParam(soap, &soap_tmp___ns1__setVideoParam, "-ns1:setVideoParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__setVideoParam(soap, soap_tmp___ns1__setVideoParam.ns1__setVideoParamReq, &ns1__setVideoParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__setVideoParamRes(soap, &ns1__setVideoParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__setVideoParamRes(soap, &ns1__setVideoParamRes, "ns1:setVideoParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__setVideoParamRes(soap, &ns1__setVideoParamRes, "ns1:setVideoParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getOSDParam(struct soap *soap)
{	struct __ns1__getOSDParam soap_tmp___ns1__getOSDParam;
	struct _ns1__getOSDParamRes ns1__getOSDParamRes;
	soap_default__ns1__getOSDParamRes(soap, &ns1__getOSDParamRes);
	soap_default___ns1__getOSDParam(soap, &soap_tmp___ns1__getOSDParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getOSDParam(soap, &soap_tmp___ns1__getOSDParam, "-ns1:getOSDParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getOSDParam(soap, soap_tmp___ns1__getOSDParam.ns1__getOSDParamReq, &ns1__getOSDParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getOSDParamRes(soap, &ns1__getOSDParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getOSDParamRes(soap, &ns1__getOSDParamRes, "ns1:getOSDParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getOSDParamRes(soap, &ns1__getOSDParamRes, "ns1:getOSDParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__setOSDParam(struct soap *soap)
{	struct __ns1__setOSDParam soap_tmp___ns1__setOSDParam;
	struct _ns1__setOSDParamRes ns1__setOSDParamRes;
	soap_default__ns1__setOSDParamRes(soap, &ns1__setOSDParamRes);
	soap_default___ns1__setOSDParam(soap, &soap_tmp___ns1__setOSDParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__setOSDParam(soap, &soap_tmp___ns1__setOSDParam, "-ns1:setOSDParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__setOSDParam(soap, soap_tmp___ns1__setOSDParam.ns1__setOSDParamReq, &ns1__setOSDParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__setOSDParamRes(soap, &ns1__setOSDParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__setOSDParamRes(soap, &ns1__setOSDParamRes, "ns1:setOSDParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__setOSDParamRes(soap, &ns1__setOSDParamRes, "ns1:setOSDParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getTime(struct soap *soap)
{	struct __ns1__getTime soap_tmp___ns1__getTime;
	struct _ns1__getTimeRes ns1__getTimeRes;
	soap_default__ns1__getTimeRes(soap, &ns1__getTimeRes);
	soap_default___ns1__getTime(soap, &soap_tmp___ns1__getTime);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getTime(soap, &soap_tmp___ns1__getTime, "-ns1:getTime", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getTime(soap, soap_tmp___ns1__getTime.ns1__getTimeReq, &ns1__getTimeRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getTimeRes(soap, &ns1__getTimeRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getTimeRes(soap, &ns1__getTimeRes, "ns1:getTimeRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getTimeRes(soap, &ns1__getTimeRes, "ns1:getTimeRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__setTime(struct soap *soap)
{	struct __ns1__setTime soap_tmp___ns1__setTime;
	struct _ns1__setTimeRes ns1__setTimeRes;
	soap_default__ns1__setTimeRes(soap, &ns1__setTimeRes);
	soap_default___ns1__setTime(soap, &soap_tmp___ns1__setTime);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__setTime(soap, &soap_tmp___ns1__setTime, "-ns1:setTime", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__setTime(soap, soap_tmp___ns1__setTime.ns1__setTimeReq, &ns1__setTimeRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__setTimeRes(soap, &ns1__setTimeRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__setTimeRes(soap, &ns1__setTimeRes, "ns1:setTimeRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__setTimeRes(soap, &ns1__setTimeRes, "ns1:setTimeRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getVMDParam(struct soap *soap)
{	struct __ns1__getVMDParam soap_tmp___ns1__getVMDParam;
	struct _ns1__getVMDParamRes ns1__getVMDParamRes;
	soap_default__ns1__getVMDParamRes(soap, &ns1__getVMDParamRes);
	soap_default___ns1__getVMDParam(soap, &soap_tmp___ns1__getVMDParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getVMDParam(soap, &soap_tmp___ns1__getVMDParam, "-ns1:getVMDParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getVMDParam(soap, soap_tmp___ns1__getVMDParam.ns1__getVMDParamReq, &ns1__getVMDParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getVMDParamRes(soap, &ns1__getVMDParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getVMDParamRes(soap, &ns1__getVMDParamRes, "ns1:getVMDParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getVMDParamRes(soap, &ns1__getVMDParamRes, "ns1:getVMDParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__setVMDParam(struct soap *soap)
{	struct __ns1__setVMDParam soap_tmp___ns1__setVMDParam;
	struct _ns1__setVMDParamRes ns1__setVMDParamRes;
	soap_default__ns1__setVMDParamRes(soap, &ns1__setVMDParamRes);
	soap_default___ns1__setVMDParam(soap, &soap_tmp___ns1__setVMDParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__setVMDParam(soap, &soap_tmp___ns1__setVMDParam, "-ns1:setVMDParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__setVMDParam(soap, soap_tmp___ns1__setVMDParam.ns1__setVMDParamReq, &ns1__setVMDParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__setVMDParamRes(soap, &ns1__setVMDParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__setVMDParamRes(soap, &ns1__setVMDParamRes, "ns1:setVMDParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__setVMDParamRes(soap, &ns1__setVMDParamRes, "ns1:setVMDParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getPrivacyMaskParam(struct soap *soap)
{	struct __ns1__getPrivacyMaskParam soap_tmp___ns1__getPrivacyMaskParam;
	struct _ns1__getPrivacyMaskParamRes ns1__getPrivacyMaskParamRes;
	soap_default__ns1__getPrivacyMaskParamRes(soap, &ns1__getPrivacyMaskParamRes);
	soap_default___ns1__getPrivacyMaskParam(soap, &soap_tmp___ns1__getPrivacyMaskParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getPrivacyMaskParam(soap, &soap_tmp___ns1__getPrivacyMaskParam, "-ns1:getPrivacyMaskParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getPrivacyMaskParam(soap, soap_tmp___ns1__getPrivacyMaskParam.ns1__getPrivacyMaskParamReq, &ns1__getPrivacyMaskParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getPrivacyMaskParamRes(soap, &ns1__getPrivacyMaskParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getPrivacyMaskParamRes(soap, &ns1__getPrivacyMaskParamRes, "ns1:getPrivacyMaskParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getPrivacyMaskParamRes(soap, &ns1__getPrivacyMaskParamRes, "ns1:getPrivacyMaskParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__setPrivacyMaskParam(struct soap *soap)
{	struct __ns1__setPrivacyMaskParam soap_tmp___ns1__setPrivacyMaskParam;
	struct _ns1__setPrivacyMaskParamRes ns1__setPrivacyMaskParamRes;
	soap_default__ns1__setPrivacyMaskParamRes(soap, &ns1__setPrivacyMaskParamRes);
	soap_default___ns1__setPrivacyMaskParam(soap, &soap_tmp___ns1__setPrivacyMaskParam);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__setPrivacyMaskParam(soap, &soap_tmp___ns1__setPrivacyMaskParam, "-ns1:setPrivacyMaskParam", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__setPrivacyMaskParam(soap, soap_tmp___ns1__setPrivacyMaskParam.ns1__setPrivacyMaskParamReq, &ns1__setPrivacyMaskParamRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__setPrivacyMaskParamRes(soap, &ns1__setPrivacyMaskParamRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__setPrivacyMaskParamRes(soap, &ns1__setPrivacyMaskParamRes, "ns1:setPrivacyMaskParamRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__setPrivacyMaskParamRes(soap, &ns1__setPrivacyMaskParamRes, "ns1:setPrivacyMaskParamRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getPlayUrl(struct soap *soap)
{	struct __ns1__getPlayUrl soap_tmp___ns1__getPlayUrl;
	struct _ns1__getPlayUrlRes ns1__getPlayUrlRes;
	soap_default__ns1__getPlayUrlRes(soap, &ns1__getPlayUrlRes);
	soap_default___ns1__getPlayUrl(soap, &soap_tmp___ns1__getPlayUrl);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getPlayUrl(soap, &soap_tmp___ns1__getPlayUrl, "-ns1:getPlayUrl", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getPlayUrl(soap, soap_tmp___ns1__getPlayUrl.ns1__getPlayUrlReq, &ns1__getPlayUrlRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getPlayUrlRes(soap, &ns1__getPlayUrlRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getPlayUrlRes(soap, &ns1__getPlayUrlRes, "ns1:getPlayUrlRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getPlayUrlRes(soap, &ns1__getPlayUrlRes, "ns1:getPlayUrlRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__getVODUrl(struct soap *soap)
{	struct __ns1__getVODUrl soap_tmp___ns1__getVODUrl;
	struct _ns1__getVODUrlRes ns1__getVODUrlRes;
	soap_default__ns1__getVODUrlRes(soap, &ns1__getVODUrlRes);
	soap_default___ns1__getVODUrl(soap, &soap_tmp___ns1__getVODUrl);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__getVODUrl(soap, &soap_tmp___ns1__getVODUrl, "-ns1:getVODUrl", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__getVODUrl(soap, soap_tmp___ns1__getVODUrl.ns1__getVODUrlReq, &ns1__getVODUrlRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__getVODUrlRes(soap, &ns1__getVODUrlRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__getVODUrlRes(soap, &ns1__getVODUrlRes, "ns1:getVODUrlRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__getVODUrlRes(soap, &ns1__getVODUrlRes, "ns1:getVODUrlRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__vodSearch(struct soap *soap)
{	struct __ns1__vodSearch soap_tmp___ns1__vodSearch;
	struct _ns1__vodSearchRes ns1__vodSearchRes;
	soap_default__ns1__vodSearchRes(soap, &ns1__vodSearchRes);
	soap_default___ns1__vodSearch(soap, &soap_tmp___ns1__vodSearch);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__vodSearch(soap, &soap_tmp___ns1__vodSearch, "-ns1:vodSearch", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__vodSearch(soap, soap_tmp___ns1__vodSearch.ns1__vodSearchReq, &ns1__vodSearchRes);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__ns1__vodSearchRes(soap, &ns1__vodSearchRes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__ns1__vodSearchRes(soap, &ns1__vodSearchRes, "ns1:vodSearchRes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__ns1__vodSearchRes(soap, &ns1__vodSearchRes, "ns1:vodSearchRes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
